### ISSUE TITLE
Search bar broken

### ISSUE THREAD

**Issue by listguy** [KorenEzri/pokedex#2]
Search bar is not working. Trying to search a pokemon but nothing happens

**Comment by KorenEzri** [comment]
Seems to work for me, both on my PC and on my phone, and Yuval reported his works too. Can you describe the issue you're experiencing with detail?

https://user-images.githubusercontent.com/73742515/112501148-aa305280-8d91-11eb-9075-c4ae50290bca.mp4

**Comment by listguy** [comment]
Ok works now some how 🤷‍♂️
